version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DISPLAY=${DISPLAY}       # récupère le DISPLAY de l’hôte
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix   # monte le socket X11
    # (le reste de vos variables et dépendances)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

volumes:
  mysql_data:
